server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug
positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://iot-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: app
        regex: '/(.*)'
        replacement: '$1'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: stream
      - source_labels: ['__meta_docker_container_path']
        target_label: __path__
  - job_name: app_files
    static_configs:
      - targets:
          - localhost
        labels:
          app: mqtt-broker
          __path__: /var/log/external/mqtt-broker/*